version: '3.8'

services:
  #########################################
  #   Setup Database container
  #########################################
  database:
    container_name: ctc-database-prod
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${MYSQL_HOST_PORT}:${DB_PORT}"
    volumes:
      - ctc-prod-db:/var/lib/mysql
    networks:
      - ctc-app-network-prod
  #########################################
  #   Setup Laravel App container
  #########################################
  app:
    depends_on:
      - database
    container_name: ctc-app-prod
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_APP_IMAGE}:prod
    build:
      context: .
      target: production
    volumes:
      - .:/var/www
      - ./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
    ports:
      - "${APPLICATION_HOST_PORT}:${APPLICATION_CONTAINER_PORT}"
    environment:
      - APP_ENV=${APP_ENV}
      - APP_NAME=${APP_NAME}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APPLICATION_ADMIN_FIRST_NAME=${APPLICATION_ADMIN_FIRST_NAME}
      - APPLICATION_ADMIN_LAST_NAME=${APPLICATION_ADMIN_LAST_NAME}
      - APPLICATION_ADMIN_EMAIL=${APPLICATION_ADMIN_EMAIL}
      - APPLICATION_MEMBER_FIRST_NAME=${APPLICATION_MEMBER_FIRST_NAME}
      - APPLICATION_MEMBER_LAST_NAME=${APPLICATION_MEMBER_LAST_NAME}
      - APPLICATION_MEMBER_EMAIL=${APPLICATION_MEMBER_EMAIL}
      - APPLICATION_PASSWORD=${APPLICATION_PASSWORD}
    networks:
      - ctc-app-network-prod

networks:
  ctc-app-network-prod:
    driver: bridge

volumes:
  ctc-prod-db:
